#ifndef H_CO_BCB_XE3_ON3QFFJE
#define H_CO_BCB_XE3_ON3QFFJE

/*lint -save -w1 */

// PC-lint implicitly #include's this header file at the outset of
// processing for each primary source file because of the -header() option
// in co-Embarcadero-C++Buider-XE3.lnt.

#ifdef _lint /* Make sure no compiler comes this way */

/*
   The headers included below must be generated from the XML file
   generated by invoking bcc32.exe with -Zxm.

   Unfortunately, it's not quite straightforward to actually use this
   option with the first release of the bcc32/XE3: only the command-line
   compiler accepts it.  When a build is run from within the IDE,
   bcc32.exe is not actually invoked. Instead, the IDE uses a DLL that
   implements most of the functionality of bcc32.exe, but the
   implementation of -Zxm is apparently not part of that DLL.

   So what to do?

   It's still possible to invoke the compiler from a batch script with
   settings equivalent to the build performed by the IDE by doing the
   following:

    0)
    Place an empty source (call it empty.cpp) in the project directory and
    add it the project; in that file, insert the line:
        #pragma option -Zxm=lint_cppmac.xml
    ... and save it.

    1)
    Enable the display of Build messages:
    "View" menu -> Messages, "Build" tab

    2)
    Build the project.

    3)
    Look for the line:
       bcc32 command line for "empty.cpp"
    ... in the Build messages window; select & copy it.

    4)
    Paste the command into a batch script file (say, "a.bat"); save it in
    the project directory. After pasting, remove whitespace & newlines
    that the IDE inserted for presentation purposes.

    5)
    open cmd.exe; chdir to the project directory and run the batch script.

    Now the file lint_cppmac.xml should appear in the project directory.
    Modify it so that its macro definitions are presented as ordinary
    #define directives and save the result as lint_cppmac.h. This header
    is #include'd below.
 */
#if defined(__cplusplus)
#       include "lint_cppmac.h" // DO NOT COMMENT THIS OUT. DO NOT SUPPRESS ERROR 322. (If you see an error here, check -i options and ensure that you have generated lint_cppmac.h using the output from bcc32.exe with -Zxm (see above).
#else
#       include "lint_cmac.h"  // DO NOT COMMENT THIS OUT. DO NOT SUPPRESS ERROR 322. (If you see an error here, check -i options and ensure that you have generated lint_cmac.h using the output from bcc32.exe with -Zxm (see above).
#endif

// Here is how we support Embarcadero's __classid() operator (using
// PC-lint 9.00j):
namespace System { class TMetaClass; namespace Classes {
// Lifted from Embarcadero/10.0/include/windows/rtl/System.Classes.hpp:
typedef System::TMetaClass* TComponentClass;
}} // namespace System

System::Classes::TComponentClass __lint_classid(void);
//lint ++d"__classid()=__lint_classid()"

#endif /* _lint      */
/*lint -restore */

#endif // end of include guard: H_CO_BCB_XE3_ON3QFFJE
